import type { PreviewTheme } from "./types";

export const previewThemes: PreviewTheme[] = [

  {
    id: "cobalt",
    label: "Cobalt",
    mode: "dark",
    colors: {
          "bgPrimary": "#142738",
          "textColor": "#dbf0ef",
          "headingColor": "#d3c845",
          "linkColor": "#36c99b",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#fc851e",
          "blockquoteBg": "transparent",
          "codeKeyword": "#f2dd00",
          "codeString": "#3ad900",
          "codeNumber": "#edf080",
          "codeComment": "#08f",
          "codeFunction": "#f2dd00",
          "codeBuiltin": "#3ad900",
          "codeVariable": "#0e73a2",
          "codeAttr": "#3ad900",
          "codeTag": "#905",
          "tableBorder": "#102432",
          "tableHeaderBg": "#152d3e",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },

  {
    id: "default",
    label: "Default",
    mode: "light",
    colors: {
          "bgPrimary": "#ffffff",
          "textColor": "#000000",
          "headingColor": "#0969da",
          "linkColor": "#0969da",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#d0d7de",
          "blockquoteBg": "transparent",
          "codeKeyword": "#07a",
          "codeString": "#690",
          "codeNumber": "#905",
          "codeComment": "#708090",
          "codeFunction": "#dd4a68",
          "codeBuiltin": "#690",
          "codeVariable": "#e90",
          "codeAttr": "#690",
          "codeTag": "#905",
          "tableBorder": "#808080",
          "tableHeaderBg": "#ffffff",
          "tableRowStripe": "#f6f8fa"
    },
  },

  {
    id: "solarized-dark",
    label: "Solarized Dark",
    mode: "dark",
    colors: {
          "bgPrimary": "#0b3742",
          "textColor": "#9ba6a4",
          "headingColor": "#abb5b4",
          "linkColor": "#3fc6b4",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#2c9285",
          "blockquoteBg": "transparent",
          "codeKeyword": "#69b5d8",
          "codeString": "#fc8a64",
          "codeNumber": "#31b1ed",
          "codeComment": "#a6a6a6",
          "codeFunction": "#69b5d8",
          "codeBuiltin": "#fc8a64",
          "codeVariable": "#0e73a2",
          "codeAttr": "#fc8a64",
          "codeTag": "#905",
          "tableBorder": "#032c36",
          "tableHeaderBg": "#062128",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },

  {
    id: "solarized-light",
    label: "Solarized Light",
    mode: "light",
    colors: {
          "bgPrimary": "#fdf6e3",
          "textColor": "#323e45",
          "headingColor": "#3b4f54",
          "linkColor": "#ac7514",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#a56812",
          "blockquoteBg": "transparent",
          "codeKeyword": "#1082b7",
          "codeString": "#d33905",
          "codeNumber": "#107fb2",
          "codeComment": "#838383",
          "codeFunction": "#1082b7",
          "codeBuiltin": "#d33905",
          "codeVariable": "#0e73a2",
          "codeAttr": "#d33905",
          "codeTag": "#905",
          "tableBorder": "rgba(147,161,161,.5)",
          "tableHeaderBg": "#fcf4dc",
          "tableRowStripe": "#f6f8fa"
    },
  },

  {
    id: "toothpaste",
    label: "Toothpaste",
    mode: "dark",
    colors: {
          "bgPrimary": "#222e33",
          "textColor": "#dce3e8",
          "headingColor": "#83d1dd",
          "linkColor": "#d65c5c",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#c7bf7f",
          "blockquoteBg": "transparent",
          "codeKeyword": "#71bd61",
          "codeString": "#e78d90",
          "codeNumber": "#cdcc81",
          "codeComment": "#8ebec7",
          "codeFunction": "#71bd61",
          "codeBuiltin": "#e78d90",
          "codeVariable": "#0e73a2",
          "codeAttr": "#e78d90",
          "codeTag": "#905",
          "tableBorder": "#0f1517",
          "tableHeaderBg": "#12181b",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },

  {
    id: "typo",
    label: "Typo",
    mode: "light",
    colors: {
          "bgPrimary": "#ffffff",
          "textColor": "#333333",
          "headingColor": "#000",
          "linkColor": "#1abc9c",
          "linkHoverColor": "#555",
          "blockquoteBorder": "#1abc9c",
          "blockquoteBg": "transparent",
          "codeKeyword": "#277fbe",
          "codeString": "#277fbe",
          "codeNumber": "#1b6498",
          "codeComment": "#bdc3b7",
          "codeFunction": "#66a329",
          "codeBuiltin": "#e36209",
          "codeVariable": "#8dcefc",
          "codeAttr": "#66a329",
          "codeTag": "#1b6498",
          "tableBorder": "#ddd",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
];
