import type { PreviewTheme } from "./types";

export const previewThemes: PreviewTheme[] = [
  {
    id: "ayu-mirage",
    label: "Ayu Mirage",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#9faab9",
          "linkColor": "#fecb66",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#fecb66",
          "blockquoteBg": "transparent",
          "codeKeyword": "#fea759",
          "codeString": "#76d0ff",
          "codeNumber": "#b0e27d",
          "codeComment": "#7e91a2",
          "codeFunction": "#fea759",
          "codeBuiltin": "#76d0ff",
          "codeVariable": "#0e73a2",
          "codeAttr": "#76d0ff",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "ayu",
    label: "Ayu",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#4d5255",
          "linkColor": "#e66700",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#ff6a00",
          "blockquoteBg": "transparent",
          "codeKeyword": "#2576b1",
          "codeString": "#357f1e",
          "codeNumber": "#0087b2",
          "codeComment": "#7f7e7d",
          "codeFunction": "#2576b1",
          "codeBuiltin": "#357f1e",
          "codeVariable": "#0e73a2",
          "codeAttr": "#357f1e",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "bear-default",
    label: "Bear Default",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#262626",
          "linkColor": "#2478c5",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#353535",
          "blockquoteBg": "transparent",
          "codeKeyword": "#2478c5",
          "codeString": "#b43d15",
          "codeNumber": "#0b5d83",
          "codeComment": "#575757",
          "codeFunction": "#2478c5",
          "codeBuiltin": "#b43d15",
          "codeVariable": "#0e73a2",
          "codeAttr": "#b43d15",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "charcoal",
    label: "Charcoal",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#acacac",
          "linkColor": "#abc4cf",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#9bb7c4",
          "blockquoteBg": "transparent",
          "codeKeyword": "#4883b9",
          "codeString": "#c7c67a",
          "codeNumber": "#4883b9",
          "codeComment": "#808080",
          "codeFunction": "#4883b9",
          "codeBuiltin": "#c7c67a",
          "codeVariable": "#0e73a2",
          "codeAttr": "#c7c67a",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "cobalt",
    label: "Cobalt",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#d3c845",
          "linkColor": "#36c99b",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#fc851e",
          "blockquoteBg": "transparent",
          "codeKeyword": "#f2dd00",
          "codeString": "#3ad900",
          "codeNumber": "#edf080",
          "codeComment": "#08f",
          "codeFunction": "#f2dd00",
          "codeBuiltin": "#3ad900",
          "codeVariable": "#0e73a2",
          "codeAttr": "#3ad900",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "contrast",
    label: "Contrast",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#262626",
          "linkColor": "#2478c5",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#2478c5",
          "blockquoteBg": "transparent",
          "codeKeyword": "#2478c5",
          "codeString": "#b43d15",
          "codeNumber": "#0b5d83",
          "codeComment": "#575757",
          "codeFunction": "#2478c5",
          "codeBuiltin": "#b43d15",
          "codeVariable": "#0e73a2",
          "codeAttr": "#b43d15",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "d-boring",
    label: "D Boring",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#000",
          "linkColor": "#50708b",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#7f7f7f",
          "blockquoteBg": "transparent",
          "codeKeyword": "#aa3f95",
          "codeString": "#e95800",
          "codeNumber": "#009305",
          "codeComment": "#878b88",
          "codeFunction": "#aa3f95",
          "codeBuiltin": "#e95800",
          "codeVariable": "#0e73a2",
          "codeAttr": "#e95800",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "dark-graphite",
    label: "Dark Graphite",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#cbdbe5",
          "linkColor": "#6bcafb",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#4aa8fb",
          "blockquoteBg": "transparent",
          "codeKeyword": "#aeedda",
          "codeString": "#e6772f",
          "codeNumber": "#aac97f",
          "codeComment": "#7f8c97",
          "codeFunction": "#aeedda",
          "codeBuiltin": "#e6772f",
          "codeVariable": "#0e73a2",
          "codeAttr": "#e6772f",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "default",
    label: "Default",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#0969da",
          "linkColor": "#0969da",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#d0d7de",
          "blockquoteBg": "transparent",
          "codeKeyword": "#07a",
          "codeString": "#690",
          "codeNumber": "#905",
          "codeComment": "#708090",
          "codeFunction": "#dd4a68",
          "codeBuiltin": "#690",
          "codeVariable": "#e90",
          "codeAttr": "#690",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "dieci",
    label: "Dieci",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#fcce23",
          "linkColor": "#e39209",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#f29429",
          "blockquoteBg": "transparent",
          "codeKeyword": "#e38e13",
          "codeString": "#e48952",
          "codeNumber": "#cb4343",
          "codeComment": "#a3a6a9",
          "codeFunction": "#e38e13",
          "codeBuiltin": "#e48952",
          "codeVariable": "#0e73a2",
          "codeAttr": "#e48952",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "dracula",
    label: "Dracula",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#50fa7b",
          "linkColor": "#8be9fd",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#cdaef9",
          "blockquoteBg": "transparent",
          "codeKeyword": "#73d5e9",
          "codeString": "#f4f99d",
          "codeNumber": "#caa9fa",
          "codeComment": "#7587b3",
          "codeFunction": "#73d5e9",
          "codeBuiltin": "#f4f99d",
          "codeVariable": "#0e73a2",
          "codeAttr": "#f4f99d",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "duotone-heat",
    label: "Duotone Heat",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#8a4aa9",
          "linkColor": "#b747af",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#ca7cd0",
          "blockquoteBg": "transparent",
          "codeKeyword": "#8f589a",
          "codeString": "#ad435b",
          "codeNumber": "#49a367",
          "codeComment": "#928e93",
          "codeFunction": "#8f589a",
          "codeBuiltin": "#ad435b",
          "codeVariable": "#0e73a2",
          "codeAttr": "#ad435b",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "duotone-light",
    label: "Duotone Light",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#635a47",
          "linkColor": "#0b3587",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#7390c9",
          "blockquoteBg": "transparent",
          "codeKeyword": "#0b3587",
          "codeString": "#7390c9",
          "codeNumber": "#063189",
          "codeComment": "#b19665",
          "codeFunction": "#0b3587",
          "codeBuiltin": "#7390c9",
          "codeVariable": "#0e73a2",
          "codeAttr": "#7390c9",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "gandalf",
    label: "Gandalf",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#3d516d",
          "linkColor": "#80394b",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#a04c6b",
          "blockquoteBg": "transparent",
          "codeKeyword": "#a944aa",
          "codeString": "#c34900",
          "codeNumber": "#4e7f1b",
          "codeComment": "#7c8291",
          "codeFunction": "#a944aa",
          "codeBuiltin": "#c34900",
          "codeVariable": "#0e73a2",
          "codeAttr": "#c34900",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "github-light",
    label: "Github Light",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#0969da",
          "linkColor": "#0969da",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#d0d7de",
          "blockquoteBg": "transparent",
          "codeKeyword": "#d73a49",
          "codeString": "#032f62",
          "codeNumber": "#005cc5",
          "codeComment": "#6a737d",
          "codeFunction": "#6f42c1",
          "codeBuiltin": "#e36209",
          "codeVariable": "#24292e",
          "codeAttr": "#005cc5",
          "codeTag": "#22863a",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "gotham",
    label: "Gotham",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#2eb88c",
          "linkColor": "#f2825a",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#2aa889",
          "blockquoteBg": "transparent",
          "codeKeyword": "#a0a2b6",
          "codeString": "#ee8b68",
          "codeNumber": "#7676c1",
          "codeComment": "#6dabba",
          "codeFunction": "#a0a2b6",
          "codeBuiltin": "#ee8b68",
          "codeVariable": "#0e73a2",
          "codeAttr": "#ee8b68",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "indigo",
    label: "Indigo",
    mode: "light",
    colors: {
          "textColor": "#595959",
          "headingColor": "#0969da",
          "linkColor": "#667eea",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#7f9cf5",
          "blockquoteBg": "#ebf4ff",
          "codeKeyword": "#66d9ef",
          "codeString": "#a6e22e",
          "codeNumber": "#ae81ff",
          "codeComment": "#8292a2",
          "codeFunction": "#e6db74",
          "codeBuiltin": "#a6e22e",
          "codeVariable": "#f8f8f2",
          "codeAttr": "#a6e22e",
          "codeTag": "#f92672",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "jzman",
    label: "Jzman",
    mode: "light",
    colors: {
          "textColor": "#3e3e3e",
          "headingColor": "#0969da",
          "linkColor": "#3e3e3e",
          "linkHoverColor": "#275b8c",
          "blockquoteBorder": "#cbcbcb",
          "blockquoteBg": "#f8f8f8",
          "codeKeyword": "#07a",
          "codeString": "#690",
          "codeNumber": "#905",
          "codeComment": "#708090",
          "codeFunction": "#dd4a68",
          "codeBuiltin": "#690",
          "codeVariable": "#e90",
          "codeAttr": "#690",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#fcfcfc"
    },
  },
  {
    id: "lark-bold-color",
    label: "Lark Bold Color",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#0969da",
          "linkColor": "#3370ff",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#3370ff",
          "blockquoteBg": "transparent",
          "codeKeyword": "#07a",
          "codeString": "#690",
          "codeNumber": "#905",
          "codeComment": "#708090",
          "codeFunction": "#dd4a68",
          "codeBuiltin": "#690",
          "codeVariable": "#e90",
          "codeAttr": "#690",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "lark",
    label: "Lark",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#0969da",
          "linkColor": "#3370ff",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#3370ff",
          "blockquoteBg": "transparent",
          "codeKeyword": "#07a",
          "codeString": "#690",
          "codeNumber": "#905",
          "codeComment": "#708090",
          "codeFunction": "#dd4a68",
          "codeBuiltin": "#690",
          "codeVariable": "#e90",
          "codeAttr": "#690",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "lighthouse",
    label: "Lighthouse",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#fbef89",
          "linkColor": "#7bceab",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#d15f26",
          "blockquoteBg": "transparent",
          "codeKeyword": "#7bceab",
          "codeString": "#ff8b48",
          "codeNumber": "#c092af",
          "codeComment": "#787d92",
          "codeFunction": "#7bceab",
          "codeBuiltin": "#ff8b48",
          "codeVariable": "#0e73a2",
          "codeAttr": "#ff8b48",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "modern-zen",
    label: "Modern Zen",
    mode: "light",
    colors: {
          "textColor": "#333",
          "headingColor": "#111",
          "linkColor": "#444",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#ccc",
          "blockquoteBg": "transparent",
          "codeKeyword": "#d73a49",
          "codeString": "#032f62",
          "codeNumber": "#005cc5",
          "codeComment": "#6a737d",
          "codeFunction": "#6f42c1",
          "codeBuiltin": "#e36209",
          "codeVariable": "#24292e",
          "codeAttr": "#005cc5",
          "codeTag": "#22863a",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "nord",
    label: "Nord",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#d9dde7",
          "linkColor": "#a7bd90",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#90b9c9",
          "blockquoteBg": "transparent",
          "codeKeyword": "#94bece",
          "codeString": "#e39e86",
          "codeNumber": "#a7bd90",
          "codeComment": "#a9b3d2",
          "codeFunction": "#94bece",
          "codeBuiltin": "#e39e86",
          "codeVariable": "#0e73a2",
          "codeAttr": "#e39e86",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "olive-dunk",
    label: "Olive Dunk",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#2b6451",
          "linkColor": "#215f4f",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#95afa3",
          "blockquoteBg": "transparent",
          "codeKeyword": "#a96498",
          "codeString": "#d06d1f",
          "codeNumber": "#337f00",
          "codeComment": "#878b88",
          "codeFunction": "#a96498",
          "codeBuiltin": "#d06d1f",
          "codeVariable": "#0e73a2",
          "codeAttr": "#d06d1f",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "one-dark",
    label: "One Dark",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#e06c75",
          "linkColor": "#61afef",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#5c6370",
          "blockquoteBg": "transparent",
          "codeKeyword": "#c678dd",
          "codeString": "#98c379",
          "codeNumber": "#d19a66",
          "codeComment": "#5c6370",
          "codeFunction": "#61afef",
          "codeBuiltin": "#e5c07b",
          "codeVariable": "#abb2bf",
          "codeAttr": "#d19a66",
          "codeTag": "#e06c75",
          "tableBorder": "#3e4451",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "#2c313a"
    },
  },
  {
    id: "panic",
    label: "Panic",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#f9b537",
          "linkColor": "#54c1dc",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#f9b537",
          "blockquoteBg": "transparent",
          "codeKeyword": "#bca9e5",
          "codeString": "#fcc146",
          "codeNumber": "#bca9e5",
          "codeComment": "#707982",
          "codeFunction": "#bca9e5",
          "codeBuiltin": "#fcc146",
          "codeVariable": "#0e73a2",
          "codeAttr": "#fcc146",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "red-graphite",
    label: "Red Graphite",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#262626",
          "linkColor": "#de4c4f",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#e06e73",
          "blockquoteBg": "transparent",
          "codeKeyword": "#2478c5",
          "codeString": "#b43d15",
          "codeNumber": "#0b5d83",
          "codeComment": "#575757",
          "codeFunction": "#2478c5",
          "codeBuiltin": "#b43d15",
          "codeVariable": "#0e73a2",
          "codeAttr": "#b43d15",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "smartblue",
    label: "Smartblue",
    mode: "light",
    colors: {
          "textColor": "#595959",
          "headingColor": "#135ce0",
          "linkColor": "#036aca",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#b2aec5",
          "blockquoteBg": "transparent",
          "codeKeyword": "#07a",
          "codeString": "#690",
          "codeNumber": "#905",
          "codeComment": "#708090",
          "codeFunction": "#dd4a68",
          "codeBuiltin": "#690",
          "codeVariable": "#e90",
          "codeAttr": "#690",
          "codeTag": "#905",
          "tableBorder": "#dfe2e5",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "solarized-dark",
    label: "Solarized Dark",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#abb5b4",
          "linkColor": "#3fc6b4",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#2c9285",
          "blockquoteBg": "transparent",
          "codeKeyword": "#69b5d8",
          "codeString": "#fc8a64",
          "codeNumber": "#31b1ed",
          "codeComment": "#a6a6a6",
          "codeFunction": "#69b5d8",
          "codeBuiltin": "#fc8a64",
          "codeVariable": "#0e73a2",
          "codeAttr": "#fc8a64",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "solarized-light",
    label: "Solarized Light",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#3b4f54",
          "linkColor": "#ac7514",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#a56812",
          "blockquoteBg": "transparent",
          "codeKeyword": "#1082b7",
          "codeString": "#d33905",
          "codeNumber": "#107fb2",
          "codeComment": "#838383",
          "codeFunction": "#1082b7",
          "codeBuiltin": "#d33905",
          "codeVariable": "#0e73a2",
          "codeAttr": "#d33905",
          "codeTag": "#905",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "toothpaste",
    label: "Toothpaste",
    mode: "dark",
    colors: {
          "textColor": "#abb2bf",
          "headingColor": "#83d1dd",
          "linkColor": "#d65c5c",
          "linkHoverColor": "#61afef",
          "blockquoteBorder": "#c7bf7f",
          "blockquoteBg": "transparent",
          "codeKeyword": "#71bd61",
          "codeString": "#e78d90",
          "codeNumber": "#cdcc81",
          "codeComment": "#8ebec7",
          "codeFunction": "#71bd61",
          "codeBuiltin": "#e78d90",
          "codeVariable": "#0e73a2",
          "codeAttr": "#e78d90",
          "codeTag": "#905",
          "tableBorder": "rgba(255,255,255,0.12)",
          "tableHeaderBg": "#1a1a1a",
          "tableRowStripe": "rgba(255,255,255,0.03)"
    },
  },
  {
    id: "typo",
    label: "Typo",
    mode: "light",
    colors: {
          "textColor": "#24292f",
          "headingColor": "#000",
          "linkColor": "#1abc9c",
          "linkHoverColor": "#555",
          "blockquoteBorder": "#1abc9c",
          "blockquoteBg": "transparent",
          "codeKeyword": "#277fbe",
          "codeString": "#277fbe",
          "codeNumber": "#1b6498",
          "codeComment": "#bdc3b7",
          "codeFunction": "#66a329",
          "codeBuiltin": "#e36209",
          "codeVariable": "#8dcefc",
          "codeAttr": "#66a329",
          "codeTag": "#1b6498",
          "tableBorder": "#ddd",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#f6f8fa"
    },
  },
  {
    id: "v-green",
    label: "V Green",
    mode: "light",
    colors: {
          "textColor": "#333",
          "headingColor": "#0969da",
          "linkColor": "#333",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "rgba(62,175,124,.6)",
          "blockquoteBg": "#f8f8f8",
          "codeKeyword": "#d73a49",
          "codeString": "#032f62",
          "codeNumber": "#005cc5",
          "codeComment": "#6a737d",
          "codeFunction": "#6f42c1",
          "codeBuiltin": "#e36209",
          "codeVariable": "#24292e",
          "codeAttr": "#005cc5",
          "codeTag": "#22863a",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "rgba(62,175,124,.2)"
    },
  },
  {
    id: "vue",
    label: "Vue",
    mode: "light",
    colors: {
          "textColor": "#34495e",
          "headingColor": "#0969da",
          "linkColor": "#42b983",
          "linkHoverColor": "#0969da",
          "blockquoteBorder": "#42b983",
          "blockquoteBg": "rgba(66,185,131,.1)",
          "codeKeyword": "#277fbe",
          "codeString": "#277fbe",
          "codeNumber": "#1b6498",
          "codeComment": "#bdc3b7",
          "codeFunction": "#66a329",
          "codeBuiltin": "#e36209",
          "codeVariable": "#8dcefc",
          "codeAttr": "#66a329",
          "codeTag": "#1b6498",
          "tableBorder": "#d0d7de",
          "tableHeaderBg": "#f6f8fa",
          "tableRowStripe": "#fafafa"
    },
  },
];
